### ISSUE TITLE
Replace some quick navigation command in the Extended Virtual Buffer feature

### ISSUE THREAD

**Issue by HBM2001** [paulber19/NVDAExtensionGlobalPlugin#16]
Hi, in the upcoming release of NVDA 2024.2, a new quick navigation command has been added with the keystrokes p and Shift + p to move to the next/previous  text paragraph. However, similar shortcuts already exist in the Extended Virtual Buffer feature. To avoid conflict with the new navigation commands, I suggest replacing the old shortcuts in the Extended Virtual Buffer with alternative keystroke combinations.
I have been a long-time user of this add-on and I absolutely love it. Thank you for creating such an amazing addon!

**Comment by paulber19** [comment]
HI.
Thank you very much for pointing this out to me.
I'll take care of it.
Best regards.
Paul.
