### ISSUE TITLE
Add-on has very serious issues with NVDA Alpha 22665

### ISSUE THREAD

**Issue by amirsol81** [paulber19/NVDAExtensionGlobalPlugin#2]
After installing NVDA Alpha 22665, almost all components of the Global Plug-in stopped functioning. For instance, the plug-in's submenu no longer appears under NVDA's Preferences submenu, the shortcuts used to copy last spoken phrases to the clipboard don't function, the clipboard-echo announcements don't work, items in the System Tray can no longer be listed with Insert+F11, etc.
The add-on appears to be enabled but doesn't operate as expected.
BTW it has also affected a couple of other add-ons such as the super-useful Columns Review.
This is with Win 10 Pro 64-Bit 21H1.

**Comment by paulber19** [comment]
Hi,
Thank you for your interest in this add-on, but for the moment it is normal.
There is no version that is fully compatible with the alpha versions 
that changes every day.
I am waiting for the release of the beta version to update this add-on.
For now, it's best to stick with NVDA version 2020.4 and 9.7 of the add-on.
Best regards.
Paul.
