### ISSUE TITLE
Add-ons conflict with Access8math

### ISSUE THREAD

**Issue by cary-rowen** [paulber19/NVDAExtensionGlobalPlugin#5]
Hi @paulber19 

access8math, github repo: https://github.com/tsengwoody/Access8Math

Install both access8math and NVDA global commands extension;

Try inserting a math expression by pressing alt+m in Windows Notepad.

After pressing that key, try navigating the virtual menu using the up and down arrow keys, NVDA keeps silent;

After disabling the NVDA global commands extension, you can navigate the menu.

Thanks

**Comment by paulber19** [comment]
Hi.
 >Try inserting a math expression by pressing alt+m in Windows Notepad.
This command has no effect.
There is no virtual menu.
Is it a command from the Access8Math add-on or another software?
Can you give me more details?
Thanks.
Best regards.
Paul.

**Comment by cary-rowen** [comment]
hi @paulber19 

This is my fault, I overlooked.
 alt+M is the gesture of Access8Math, so you don't need to install other software,
 please press NVDA+Alt+C after opening notepad and make sure to hear "activate command gesture",
Then executing Alt+M.

Here is the version information:
- Access8math-3.2;
- nvda2021.3.4
- - Windows 10 21H2 (x64) build 19044.1586

Thanks

**Comment by cary-rowen** [comment]
Hi @paulber19 
Did you discover anything new about this?
Need more information?
Thanks

**Comment by cary-rowen** [comment]
Hi @paulber19 
I found that 11.2-dev21 has solved this problem, I will close this issue now
thanks for your efforts

**Comment by paulber19** [comment]
Hi Rowen
OK,thanks.
  I reproduced the problem.
This will be fixed in a future version.
Best regards.
Paul.
