### ISSUE TITLE
Request support for WASAPI

### ISSUE THREAD

**Issue by cary-rowen** [paulber19/NVDAExtensionGlobalPlugin#8]
Hi @paulber19 

NVDA-Alpha-28166 is the merged version of https://github.com/nvaccess/nvda/pull/14697

This makes sound separation unavailable.
"Use WASAPI for audio output" is now an option in NVDA Advanced Settings, and is checked by default.

Can you investigate and fix this?

**Comment by akash07k** [comment]
@cary-rowen  Is it fixed? asking because you marked it as completed

**Comment by cary-rowen** [comment]
Sorry, I closed it by mistake. I will reopen this.

**Comment by paulber19** [comment]
Hi,
Yes of course, I'm working on it.
Hoping to get there.
Best regards.

**Comment by cary-rowen** [comment]
You seem to have fixed it, I'm going to close this now. Thank you Paul for your efforts.
