### ISSUE TITLE
All synthesizers' settings reset after using profile selectors

### ISSUE THREAD

**Issue by sevapopov2** [paulber19/NVDAExtensionGlobalPlugin#9]
All synthesizers' settings reset after I use profile selectors.
Steps to reproduce:
1. Install RHVoice and 2 voices for it. You can find it [here](https://rhvoice.org).
2. Switch to other synthesizer and set rate, pitch and volume settings as you prefer.
3. Switch back to RHVoice.
4. Create 2 profiles for 2 selectors: each selector with the voice you have just installed in item 1.
5. Switch to one of the selectors you have just created.
6. Switch to another synthesizer you configured for 2. It's settings will be reset and they will be rate, pitch and volume 50.
Expected result:
Other synthesizers' settings shouldn't reset when selector is applied.
Actual result:
All other synthesizers' settings restore when you switch to your configured selector.
Reproduced on:
NVDA 2023.1.
Global Extensions Plugin v12.0.8.
RHVoice v1.12.0.
NVDA log is attached below.
[Switching synths bug.log](https://github.com/paulber19/NVDAExtensionGlobalPlugin/files/12329247/Switching.synths.bug.log)

**Comment by sevapopov2** [comment]
Hello,
@paulber19 Would it be possible to review this issue and fix it in the next versions? Thank you!

**Comment by paulber19** [comment]
Hi.
I think I fixed the problem with this version :
13.1.3 
<https://github.com/paulber007/AllMyNVDAAddons/raw/master/NVDAExtensionGlobalPlugin/NVDAExtensionGlobalPlugin-13.1.3.nvda-addon>

Can you confirm ?
Thanks.
Best regards.
Paul.

**Comment by sevapopov2** [comment]
Hello,
Thank you for your answer!
I have just checked and yes: the issue is fixed now!
Thank you so much for providing so important bug fix!
